=== TubaAdrienn/xml_tech/task3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="heroes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hero" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="hero">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="aliases" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="aliases">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alias" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
   
</xs:schema>

=== TubaAdrienn/xml_tech/result3.xml
<?xml version="1.0" encoding="UTF-8"?>
<heroes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="task3.xsd">
    <hero id="1">
        <name>A-Bomb</name>
        <aliases>
            <alias>Rick Jones</alias>
        </aliases>
    </hero>
    <hero id="2">
        <name>Abe Sapien</name>
        <aliases>
            <alias>Langdon Everett Caul</alias>
            <alias>Abraham Sapien</alias>
            <alias>Langdon Caul</alias>
        </aliases>
    </hero>
    <hero id="3">
        <name>Abin Sur</name>
        <aliases>
            <alias>Lagzia</alias>
        </aliases>
    </hero>
    <hero id="4">
        <name>Abomination</name>
        <aliases>
            <alias>Agent R-7</alias>
            <alias>Ravager of Worlds</alias>
        </aliases>
    </hero>
    <hero id="6">
        <name>Absorbing Man</name>
        <aliases>
            <alias>Greithoth</alias>
            <alias>"Crusher" Creel</alias>
            <alias>Rocky Davis</alias>
            <alias>Dynamite Davis</alias>
            <alias>Lightningbolt</alias>
            <alias>Prisoner #24957</alias>
        </aliases>
    </hero>
    <hero id="7">
        <name>Adam Monroe</name>
        <aliases>
            <alias>Takezo Kensei</alias>
            <alias>Richard Sanders</alias>
        </aliases>
    </hero>
    <hero id="8">
        <name>Adam Strange</name>
        <aliases>
            <alias>Warrior of Two Worlds</alias>
            <alias>Savior of Rann</alias>
        </aliases>
    </hero>
    <hero id="10">
        <name>Agent Bob</name>
        <aliases>
            <alias>Bob</alias>
            <alias>agent of Hydra</alias>
            <alias>Bob</alias>
            <alias>agent of A.I.M</alias>
        </aliases>
    </hero>
    <hero id="11">
        <name>Agent Zero</name>
        <aliases>
            <alias>Maverick</alias>
        </aliases>
    </hero>
    <hero id="13">
        <name>Ajax</name>
        <aliases>
            <alias>"Frankie"</alias>
            <alias>the A-Man</alias>
            <alias>the Attending</alias>
        </aliases>
    </hero>
    <hero id="14">
        <name>Alan Scott</name>
        <aliases>
            <alias>Green Lantern</alias>
            <alias>White King</alias>
            <alias>Sentinal</alias>
        </aliases>
    </hero>
    <hero id="15">
        <name>Alex Mercer</name>
        <aliases>
            <alias>Prototype</alias>
            <alias>Zues</alias>
            <alias>Blacklight</alias>
        </aliases>
    </hero>
    <hero id="17">
        <name>Alfred Pennyworth</name>
        <aliases>
            <alias>Alfred Beagle</alias>
        </aliases>
    </hero>
    <hero id="20">
        <name>Amazo</name>
        <aliases>
            <alias>Professor Ivos Amazing Android</alias>
            <alias>Timazo</alias>
            <alias>Humazo</alias>
            <alias>Hourmazo</alias>
        </aliases>
    </hero>
    <hero id="23">
        <name>Angel</name>
        <aliases>
            <alias>Angelus</alias>
            <alias>Twilight</alias>
        </aliases>
    </hero>
    <hero id="24">
        <name>Angel</name>
        <aliases>
            <alias>Formerly Death</alias>
            <alias>Dark Angel</alias>
            <alias>Angel</alias>
            <alias>Avenging Angel</alias>
            <alias>Archangel</alias>
        </aliases>
    </hero>
    <hero id="25">
        <name>Angel Dust</name>
        <aliases>
            <alias>Angel</alias>
            <alias>Dusty</alias>
        </aliases>
    </hero>
    <hero id="26">
        <name>Angel Salvadore</name>
        <aliases>
            <alias>Tempest</alias>
        </aliases>
    </hero>
    <hero id="28">
        <name>Animal Man</name>
        <aliases>
            <alias>The Human Zoo; A-Man; The Man with Animal Powers</alias>
        </aliases>
    </hero>
    <hero id="29">
        <name>Annihilus</name>
        <aliases>
            <alias>The Living Death That Walks</alias>
            <alias>Lord of the Negative Zone</alias>
        </aliases>
    </hero>
    <hero id="30">
        <name>Ant-Man</name>
        <aliases>
            <alias>Hank Pym</alias>
            <alias>Doctor Pym</alias>
            <alias>Ant-Man</alias>
            <alias>Goliath</alias>
            <alias>Yellowjacket</alias>
            <alias>Wasp</alias>
            <alias>Earth's Scientist Supreme</alias>
        </aliases>
    </hero>
    <hero id="31">
        <name>Ant-Man II</name>
        <aliases>
            <alias>Myrmidon</alias>
            <alias>Scott Edward Harris Lang</alias>
        </aliases>
    </hero>
    <hero id="32">
        <name>Anti-Monitor</name>
        <aliases>
            <alias>Monitor</alias>
            <alias>Mobius</alias>
        </aliases>
    </hero>
    <hero id="34">
        <name>Anti-Venom</name>
        <aliases>
            <alias>Eddie</alias>
            <alias>Edwin Brock</alias>
            <alias>Venom</alias>
            <alias>Lethal Protector</alias>
            <alias>White Venom</alias>
            <alias>998th</alias>
        </aliases>
    </hero>
    <hero id="35">
        <name>Apocalypse</name>
        <aliases>
            <alias>The Eternal One</alias>
            <alias>the High Lord</alias>
            <alias>Set</alias>
            <alias>Huitxilopochti</alias>
            <alias>Sauru</alias>
            <alias>Kali-Ma</alias>
        </aliases>
    </hero>
    <hero id="38">
        <name>Aquaman</name>
        <aliases>
            <alias>Dweller in the Depths</alias>
            <alias>Swimmer</alias>
            <alias>Waterbearer</alias>
            <alias>Mental Man</alias>
            <alias>Aquaboy</alias>
            <alias>Water Wraith</alias>
        </aliases>
    </hero>
    <hero id="39">
        <name>Arachne</name>
        <aliases>
            <alias>Spider-Woman</alias>
            <alias>Madame Web</alias>
        </aliases>
    </hero>
    <hero id="40">
        <name>Archangel</name>
        <aliases>
            <alias>War</alias>
            <alias>Dark Angel</alias>
            <alias>Death</alias>
            <alias>Avenging Angel</alias>
        </aliases>
    </hero>
    <hero id="43">
        <name>Ares</name>
        <aliases>
            <alias>God of War</alias>
            <alias>Mister Talon</alias>
            <alias>Mars</alias>
            <alias>Warhawk</alias>
        </aliases>
    </hero>
    <hero id="45">
        <name>Armor</name>
        <aliases>
            <alias>X-Girl</alias>
            <alias>Kid</alias>
        </aliases>
    </hero>
    <hero id="48">
        <name>Atlas</name>
        <aliases>
            <alias>Power Man</alias>
            <alias>Smuggler</alias>
            <alias>Goliath</alias>
            <alias>Shatterfist</alias>
            <alias>Intruder from Beyond</alias>
            <alias>Edward Jantzen</alias>
        </aliases>
    </hero>
    <hero id="49">
        <name>Atlas</name>
        <aliases>
            <alias>Atlas the Great</alias>
            <alias>Atlas the Untamed</alias>
        </aliases>
    </hero>
    <hero id="52">
        <name>Atom Girl</name>
        <aliases>
            <alias>Shrinking Violet</alias>
        </aliases>
    </hero>
    <hero id="53">
        <name>Atom II</name>
        <aliases>
            <alias>The Mighty Mite</alias>
            <alias>the Tiny Titan</alias>
            <alias>the World's Smallest Hero</alias>
        </aliases>
    </hero>
    <hero id="56">
        <name>Aurora</name>
        <aliases>
            <alias>Sister Beaubier</alias>
        </aliases>
    </hero>
    <hero id="57">
        <name>Azazel</name>
        <aliases>
            <alias>Semihazah</alias>
            <alias>Duma</alias>
            <alias>Keriel</alias>
            <alias>Mastema</alias>
            <alias>Beliar</alias>
            <alias>Gadreel</alias>
            <alias>Beelzebub</alias>
            <alias>Satan</alias>
        </aliases>
    </hero>
    <hero id="58">
        <name>Azrael</name>
        <aliases>
            <alias>Bat-Devil; Bat-Ghost</alias>
        </aliases>
    </hero>
    <hero id="61">
        <name>Banshee</name>
        <aliases>
            <alias>Death</alias>
        </aliases>
    </hero>
    <hero id="63">
        <name>Batgirl</name>
        <aliases>
            <alias>Oracle</alias>
            <alias>Bluebelle</alias>
        </aliases>
    </hero>
    <hero id="66">
        <name>Batgirl IV</name>
        <aliases>
            <alias>Kasumi</alias>
            <alias>various mundane persona,</alias>
        </aliases>
    </hero>
    <hero id="68">
        <name>Batgirl VI</name>
        <aliases>
            <alias>Steph</alias>
            <alias>Robin</alias>
            <alias>Marion Todd</alias>
            <alias>Spoiler</alias>
        </aliases>
    </hero>
    <hero id="69">
        <name>Batman</name>
        <aliases>
            <alias>Batman II</alias>
            <alias>The Tomorrow Knight</alias>
            <alias>The second Dark Knight</alias>
            <alias>The Dark Knight of Tomorrow</alias>
            <alias>Batman Beyond</alias>
        </aliases>
    </hero>
    <hero id="70">
        <name>Batman</name>
        <aliases>
            <alias>Insider</alias>
            <alias>Matches Malone</alias>
        </aliases>
    </hero>
    <hero id="71">
        <name>Batman II</name>
        <aliases>
            <alias>Dick Grayson</alias>
        </aliases>
    </hero>
    <hero id="72">
        <name>Battlestar</name>
        <aliases>
            <alias>Bucky</alias>
        </aliases>
    </hero>
    <hero id="75">
        <name>Beast</name>
        <aliases>
            <alias>Dr. McCoy</alias>
            <alias>Hanko</alias>
            <alias>Kreature</alias>
            <alias>Mutate #666</alias>
            <alias>Magilla Gorilla</alias>
            <alias>Golden Armed Boy</alias>
        </aliases>
